//this file was written with httpYac syntax


###
# @name get-id
GET http://0.0.0.0:3000/users/1 HTTP/1.1
Authorization: Bearer {{$global.jwtToken}}


# @name make-admin
PATCH http://0.0.0.0:3000/users/1 HTTP/1.1
Authorization: Bearer {{$global.jwtToken}}
Content-Type: application/json 

{
    "userType" : 1
}


###
# @name login
POST http://0.0.0.0:3000/users/sign-in HTTP/1.1
Content-Type: application/json 

{
    "username" : "uwuw",
    "password" : "Word&Uwu1819"
}

{{
    $global.jwtToken=response.parsedBody.access_token;
}}

# @name create
POST http://0.0.0.0:3000/users/sign-up HTTP/1.1
Content-Type: application/json 

{
    "username" : "uwuw",
    "email" : "uwu@gmail.com",
    "password" : "Word&Uwu1819"
}


###
# @name update-user
PATCH http://0.0.0.0:3000/users/1 HTTP/1.1
Authorization: Bearer {{$global.jwtToken}}
Content-Type: application/json 

{
    "username" : "uwuw",
    "email" : "uwuw@workout.com",
    "userType" : 1
}

###
# @name delete-user

DELETE http://0.0.0.0:3000/user/1 HTTP/1.1
Authorization: Bearer {{$global.jwtToken}}


### 
# @name refresh-login

GET http://0.0.0.0:3000/users/refresh-login
Authorization: Bearer {{$global.jwtToken}}


###
# @name all-users

GET http://0.0.0.0:3000/users
Authorization: Bearer {{$global.jwtToken}}

###
# @name unauthorized-access
GET  http://0.0.0.0:3000/users/my-info HTTP/1.1



###
# @name access
GET  http://0.0.0.0:3000/users/my-info HTTP/1.1
Authorization: Bearer {{$global.jwtToken}}




